### ISSUE TITLE
Error when train step

### ISSUE THREAD

**Issue by 1991806559** [SJoJoK/VGOS#4]
rgb_logit = self.rgbnet(rgb_feat) 
return F.linear(input, self.weight, self.bias)
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasLtMatmul( ltHandle, computeDesc.descriptor(), &alpha_val, mat1_ptr, Adesc.descriptor(), mat2_ptr, Bdesc.descriptor(), &beta_val, result_ptr, Cdesc.descriptor(), result_ptr, Cdesc.descriptor(), &heuristicResult.algo, workspace.data_ptr(), workspaceSize, at::cuda::getCurrentCUDAStream())`

It's a excellent work! I meet some problem in traing, could please help me solve it?

**Comment by SJoJoK** [comment]
Hello, we're glad you appreciate our work.

The error seems to be caused by the incorrect installation of CUBLAS, because you are executing a very simple function, that is, F.linear(). We haven't encountered such a problem. I think you can start by reorganizing the CUDA environment and then follow the standard CUDA Debug process (for example, setting the program to synchronization) to see if it is a problem of input tensor.

**Comment by 1991806559** [comment]
Thank you very much! I have solved it, but I found a new problem.
when I set the train view in blender_4v.sh: view=50 or large,  it cannot train the network with cuda kernel error, why?

ray_pts, ray_id, step_id, N_samples,  = self.sample_ray(rays_o=rays_o, rays_d=rays_d, **render_kwargs)
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.

**Comment by SJoJoK** [comment]
Hi,
Our script is tested to work with the default parameters, ensuring it runs correctly. If you encounter issues after modifying parameters, it may require some debugging on your part. Based on the error message you provided, it seems there may be a CUDA device-side assert error. This is often caused by out-of-bounds or improper memory access.

**Comment by 1991806559** [comment]
Thank you! I try to debug the program,  and I found the self.voxel_size with error, could you help me to fix it?

stepdist = stepsize * self.voxel_size
(Pdb) self.voxel_size
*** RuntimeError: CUDA error: device-side assert triggered

**Comment by SJoJoK** [comment]
It appears that the issue could be related to self.voxel_size not being properly defined or initialized. I recommend checking where self.voxel_size is defined and how it is assigned a value in your code to isolate the issue.

Please note that our support is **only** focused on addressing issues encountered while replicating the experiments described in our paper, which has been validated and widely adopted within the research community[1-4].

[1] Li, Jiahe, et al. "Dngaussian: Optimizing sparse-view 3d gaussian radiance fields with global-local depth normalization." arXiv preprint arXiv:2403.06912 (2024).
[2] Kim, Mingyu, et al. "Refined Tensorial Radiance Field: Harnessing coordinate based networks for novel view synthesis from sparse inputs." (2023).
[3] Xu, Yingjie, et al. "Learning with unreliability: Fast few-shot Voxel radiance fields with relative geometric consistency." arXiv preprint arXiv:2403.17638 (2024).
[4] Dong, Shaocong, et al. "TuneMV3D: Tuning Foundational Image Diffusion Models for Generalizable and Scalable Multiview 3D Generation."

**Comment by 1991806559** [comment]
Thank you! But I still think VGOS cannot work at the whole traindataset, and only work at 4-view?

**Comment by SJoJoK** [comment]
Firstly, all the arguments specified in blender_4v.sh are used for training in a 4-view setting, which means it's not advisable to simply modify the view parameter and use the script directly. A recommended approach is to execute a command like `python run.py --config configs/llff_3v/room.py --render_test_get_metric` and utilize your own configuration file.

Secondly, VGOS is an enhancement of DVGO (v2); thus, theoretically, if you can reconstruct a scene using DVGO, you should be able to do so with VGOS as well. However, our code might include assumptions about few-shot inputs (or to say, not using the whole dataset), so using the entire training dataset could potentially lead to some unexpected errors.
